# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os:
  - osx
  - linux
sudo: required
cache: packages
before_script:
  - sudo env PATH="$PATH" tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  - sudo env PATH="$PATH" tlmgr update --self
  - sudo env PATH="$PATH" tlmgr install inconsolata upquote courier courier-scaled helvetic
after_success:
  - Rscript -e 'covr::codecov()'
