# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os:
  - osx
  - linux
cache: packages
before_install:
  - tlmgr install inconsolata
after_success:
  - Rscript -e 'covr::codecov()'
